name: Update post lists
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          ls ${{ github.workspace }}/posts/*.html > ${{ github.workspace }}/posts.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Update posts"
          git push

